### ISSUE TITLE
Emitter is not a function

### ISSUE THREAD

**Issue by koraysels** [jkroso/flowtype#4]
I am trying to use Flowtype with browserify through npm but i get an error. 

```index.js:4 Uncaught TypeError: Emitter is not a function``` this is from the viewport node_module that Flowtype requires.. how can i fix this. I installed emitter with npm because otherwise brwoserify would not compile either. 

thanks!

**Comment by omarjcamo** [comment]
+1

**Comment by prisme** [comment]
+1
