### ISSUE TITLE
Doesn't seem to work?

### ISSUE THREAD

**Issue by JasonTheAdams** [jkroso/flowtype#6]
I'm using this with webkit and, while I see the flowtype code in the resulting file, it doesn't appear to do anything. Here's what I've got:

``` javascript
var flowtype = require("flowtype");

flowtype(document.body, {
  minimum   : '500px',
  maximum   : '1200px',
  minFont   : 16,
  maxFont   : 60,
  fontRatio : 60
});
```

Am I missing something?

**Comment by jkroso** [comment]
Yea you're using completely the wrong names:

``` js
min: 16
max: 60,
lineRatio: 60,
minWidth: '500px',
maxWidth: '1200px'
```

**Comment by JasonTheAdams** [comment]
@jkroso Bah! My bad! It's certainly doing something now, but having drastically different results from the original version of flowtype.js. I'm using this as it supports NPM use and the original doesn't. Is this a direct port or different? The following attributes get very different results as this version makes everything crazy tall and huge, while the other just makes most of the fonts a bit larger on desktop (I believe relative to the container rather than the whole window).

```
flowtype(document.body, {
  minWidth:  500,
  maxWidth:  1200,
  min:       16,
  max:       60,
  lineRatio: 1
});

$('body').flowtype({
  minimum   : 500,
  maximum   : 1200,
  minFont   : 16,
  maxFont   : 60,
  fontRatio : 60
});
```

Are these not the same?

**Comment by jkroso** [comment]
It's not a direct port. For sensible behaviour you should start with whats
in the Readme.md or in the example.html
